spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: CustomerModule
          uri: lb://CustomerService
          predicates:
            - Path=/customers/**
        - id: ProductModule
          uri: lb://ProductService
          predicates:
            - Path=/products/**
        - id: CartCommandModule
          uri: lb://ShoppingCartCommandService
          predicates:
            - Path=/carts/command/**
        - id: CartQueryModule
          uri: lb://ShoppingCartQueryService
          predicates:
            - Path=/carts/query/**
        - id: orderModule
          uri: lb://OrderService
          predicates:
            - Path=/orders/**


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,
                   http://localhost:8762/eureka
