server:
  port: 8761
spring:
  application:
    name: EurekaServer
eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
